/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVarRouteImport } from './routes/app.var'
import { Route as AppTransfersRouteImport } from './routes/app.transfers'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRefereesRouteImport } from './routes/app.referees'
import { Route as AppRankingsRouteImport } from './routes/app.rankings'
import { Route as AppPlayersRouteImport } from './routes/app.players'
import { Route as AppMinistryRouteImport } from './routes/app.ministry'
import { Route as AppLicensingRouteImport } from './routes/app.licensing'
import { Route as AppE2eRouteImport } from './routes/app.e2e'
import { Route as AppDisciplineRouteImport } from './routes/app.discipline'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppClubPortalRouteImport } from './routes/app.club-portal'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as ApiInviteUserRouteImport } from './routes/api.invite-user'
import { Route as AppMatchesIndexRouteImport } from './routes/app.matches.index'
import { Route as AppClubsIndexRouteImport } from './routes/app.clubs.index'
import { Route as AppMatchesMatchIdRouteImport } from './routes/app.matches.$matchId'
import { Route as AppClubsClubIdRouteImport } from './routes/app.clubs.$clubId'
import { Route as ApiPublicWeeklyDigestRouteImport } from './routes/api/public/weekly-digest'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVarRoute = AppVarRouteImport.update({
  id: '/var',
  path: '/var',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRefereesRoute = AppRefereesRouteImport.update({
  id: '/referees',
  path: '/referees',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayersRoute = AppPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AppRoute,
} as any)
const AppMinistryRoute = AppMinistryRouteImport.update({
  id: '/ministry',
  path: '/ministry',
  getParentRoute: () => AppRoute,
} as any)
const AppLicensingRoute = AppLicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => AppRoute,
} as any)
const AppE2eRoute = AppE2eRouteImport.update({
  id: '/e2e',
  path: '/e2e',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplineRoute = AppDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppClubPortalRoute = AppClubPortalRouteImport.update({
  id: '/club-portal',
  path: '/club-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const ApiInviteUserRoute = ApiInviteUserRouteImport.update({
  id: '/api/invite-user',
  path: '/api/invite-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMatchesIndexRoute = AppMatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsIndexRoute = AppClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesMatchIdRoute = AppMatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsClubIdRoute = AppClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWeeklyDigestRoute = ApiPublicWeeklyDigestRouteImport.update({
  id: '/api/public/weekly-digest',
  path: '/api/public/weekly-digest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/fixtures': typeof FixturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/invite-user': typeof ApiInviteUserRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/club-portal': typeof AppClubPortalRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/discipline': typeof AppDisciplineRoute
  '/app/e2e': typeof AppE2eRoute
  '/app/licensing': typeof AppLicensingRoute
  '/app/ministry': typeof AppMinistryRoute
  '/app/players': typeof AppPlayersRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/referees': typeof AppRefereesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/security': typeof AppSecurityRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/var': typeof AppVarRoute
  '/app/': typeof AppIndexRoute
  '/api/public/weekly-digest': typeof ApiPublicWeeklyDigestRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/matches/': typeof AppMatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fixtures': typeof FixturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/invite-user': typeof ApiInviteUserRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/club-portal': typeof AppClubPortalRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/discipline': typeof AppDisciplineRoute
  '/app/e2e': typeof AppE2eRoute
  '/app/licensing': typeof AppLicensingRoute
  '/app/ministry': typeof AppMinistryRoute
  '/app/players': typeof AppPlayersRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/referees': typeof AppRefereesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/security': typeof AppSecurityRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/var': typeof AppVarRoute
  '/app': typeof AppIndexRoute
  '/api/public/weekly-digest': typeof ApiPublicWeeklyDigestRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/clubs': typeof AppClubsIndexRoute
  '/app/matches': typeof AppMatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/fixtures': typeof FixturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/invite-user': typeof ApiInviteUserRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/club-portal': typeof AppClubPortalRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/discipline': typeof AppDisciplineRoute
  '/app/e2e': typeof AppE2eRoute
  '/app/licensing': typeof AppLicensingRoute
  '/app/ministry': typeof AppMinistryRoute
  '/app/players': typeof AppPlayersRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/referees': typeof AppRefereesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/security': typeof AppSecurityRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/var': typeof AppVarRoute
  '/app/': typeof AppIndexRoute
  '/api/public/weekly-digest': typeof ApiPublicWeeklyDigestRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/matches/': typeof AppMatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/fixtures'
    | '/forgot-password'
    | '/live'
    | '/reset-password'
    | '/api/invite-user'
    | '/app/assignments'
    | '/app/audit'
    | '/app/club-portal'
    | '/app/compliance'
    | '/app/discipline'
    | '/app/e2e'
    | '/app/licensing'
    | '/app/ministry'
    | '/app/players'
    | '/app/rankings'
    | '/app/referees'
    | '/app/reports'
    | '/app/security'
    | '/app/transfers'
    | '/app/var'
    | '/app/'
    | '/api/public/weekly-digest'
    | '/app/clubs/$clubId'
    | '/app/matches/$matchId'
    | '/app/clubs/'
    | '/app/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fixtures'
    | '/forgot-password'
    | '/live'
    | '/reset-password'
    | '/api/invite-user'
    | '/app/assignments'
    | '/app/audit'
    | '/app/club-portal'
    | '/app/compliance'
    | '/app/discipline'
    | '/app/e2e'
    | '/app/licensing'
    | '/app/ministry'
    | '/app/players'
    | '/app/rankings'
    | '/app/referees'
    | '/app/reports'
    | '/app/security'
    | '/app/transfers'
    | '/app/var'
    | '/app'
    | '/api/public/weekly-digest'
    | '/app/clubs/$clubId'
    | '/app/matches/$matchId'
    | '/app/clubs'
    | '/app/matches'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/fixtures'
    | '/forgot-password'
    | '/live'
    | '/reset-password'
    | '/api/invite-user'
    | '/app/assignments'
    | '/app/audit'
    | '/app/club-portal'
    | '/app/compliance'
    | '/app/discipline'
    | '/app/e2e'
    | '/app/licensing'
    | '/app/ministry'
    | '/app/players'
    | '/app/rankings'
    | '/app/referees'
    | '/app/reports'
    | '/app/security'
    | '/app/transfers'
    | '/app/var'
    | '/app/'
    | '/api/public/weekly-digest'
    | '/app/clubs/$clubId'
    | '/app/matches/$matchId'
    | '/app/clubs/'
    | '/app/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  FixturesRoute: typeof FixturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveRoute: typeof LiveRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiInviteUserRoute: typeof ApiInviteUserRoute
  ApiPublicWeeklyDigestRoute: typeof ApiPublicWeeklyDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/var': {
      id: '/app/var'
      path: '/var'
      fullPath: '/app/var'
      preLoaderRoute: typeof AppVarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transfers': {
      id: '/app/transfers'
      path: '/transfers'
      fullPath: '/app/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referees': {
      id: '/app/referees'
      path: '/referees'
      fullPath: '/app/referees'
      preLoaderRoute: typeof AppRefereesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rankings': {
      id: '/app/rankings'
      path: '/rankings'
      fullPath: '/app/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/players': {
      id: '/app/players'
      path: '/players'
      fullPath: '/app/players'
      preLoaderRoute: typeof AppPlayersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ministry': {
      id: '/app/ministry'
      path: '/ministry'
      fullPath: '/app/ministry'
      preLoaderRoute: typeof AppMinistryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/licensing': {
      id: '/app/licensing'
      path: '/licensing'
      fullPath: '/app/licensing'
      preLoaderRoute: typeof AppLicensingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/e2e': {
      id: '/app/e2e'
      path: '/e2e'
      fullPath: '/app/e2e'
      preLoaderRoute: typeof AppE2eRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discipline': {
      id: '/app/discipline'
      path: '/discipline'
      fullPath: '/app/discipline'
      preLoaderRoute: typeof AppDisciplineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/club-portal': {
      id: '/app/club-portal'
      path: '/club-portal'
      fullPath: '/app/club-portal'
      preLoaderRoute: typeof AppClubPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/invite-user': {
      id: '/api/invite-user'
      path: '/api/invite-user'
      fullPath: '/api/invite-user'
      preLoaderRoute: typeof ApiInviteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/matches/': {
      id: '/app/matches/'
      path: '/matches'
      fullPath: '/app/matches/'
      preLoaderRoute: typeof AppMatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/': {
      id: '/app/clubs/'
      path: '/clubs'
      fullPath: '/app/clubs/'
      preLoaderRoute: typeof AppClubsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches/$matchId': {
      id: '/app/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/app/matches/$matchId'
      preLoaderRoute: typeof AppMatchesMatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/$clubId': {
      id: '/app/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/app/clubs/$clubId'
      preLoaderRoute: typeof AppClubsClubIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/weekly-digest': {
      id: '/api/public/weekly-digest'
      path: '/api/public/weekly-digest'
      fullPath: '/api/public/weekly-digest'
      preLoaderRoute: typeof ApiPublicWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppClubPortalRoute: typeof AppClubPortalRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppDisciplineRoute: typeof AppDisciplineRoute
  AppE2eRoute: typeof AppE2eRoute
  AppLicensingRoute: typeof AppLicensingRoute
  AppMinistryRoute: typeof AppMinistryRoute
  AppPlayersRoute: typeof AppPlayersRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppRefereesRoute: typeof AppRefereesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppVarRoute: typeof AppVarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClubsClubIdRoute: typeof AppClubsClubIdRoute
  AppMatchesMatchIdRoute: typeof AppMatchesMatchIdRoute
  AppClubsIndexRoute: typeof AppClubsIndexRoute
  AppMatchesIndexRoute: typeof AppMatchesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAuditRoute: AppAuditRoute,
  AppClubPortalRoute: AppClubPortalRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppDisciplineRoute: AppDisciplineRoute,
  AppE2eRoute: AppE2eRoute,
  AppLicensingRoute: AppLicensingRoute,
  AppMinistryRoute: AppMinistryRoute,
  AppPlayersRoute: AppPlayersRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppRefereesRoute: AppRefereesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppVarRoute: AppVarRoute,
  AppIndexRoute: AppIndexRoute,
  AppClubsClubIdRoute: AppClubsClubIdRoute,
  AppMatchesMatchIdRoute: AppMatchesMatchIdRoute,
  AppClubsIndexRoute: AppClubsIndexRoute,
  AppMatchesIndexRoute: AppMatchesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  FixturesRoute: FixturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveRoute: LiveRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiInviteUserRoute: ApiInviteUserRoute,
  ApiPublicWeeklyDigestRoute: ApiPublicWeeklyDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
